name: sofia_app2
description: Sofía APP - App de fidelización
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"  # Compatible con Dart 3.4.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_sign_in: ^6.2.2  # Compatible con Dart 3.4.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  provider: ^6.1.2
  qr_code_scanner: ^1.0.1  # Última versión disponible
  url_launcher: ^6.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Bromello
      fonts:
        - asset: assets/fonts/Bromello-Regular.ttf